name: Example Action
on:
  push:
    branches: [master, feature/*]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test Example Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.0

      - name: Copy WASM Exec
        working-directory: example
        run: ./scripts/fetch-wasm-exec.bash

      - name: Build ASM
        env:
          GOOS: js
          GOARCH: wasm
        working-directory: example
        run: |
          go build -o ./dist/main.wasm ./action.go
          ls -la

      - name: Call Example
        uses: ./example
